### HealthCheck
GET http://localhost

### Show Events Catalog
GET http://localhost/catalog

### Create a new event
POST http://localhost/inventory
Content-Type: application/json

{
 "name": "Tears for Fears",
 "eventDateTime": "2024-10-20T10:30:00",
 "ticketsAvailable": 100
}

### Show Events Inventory
GET http://localhost/inventory