
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_catalog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 3030

    