version: "3.8"

services:
  api_gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      - CATALOG_SERVICE_URL=http://catalog:3030
      - INVENTORY_SERVICE_URL=http://inventory:3005
    ports:
      - 80:80